[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[font]
size = 12

[font.italic]
family = "Firacode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Firacode Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
opacity = 1

[window.dimensions]
columns = 82
lines = 51

[window.padding]
x = 0
y = 0

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
