#! /bin/sh
keymap=/path/to/your/keymap

echo >&2 "$@"
event=$1 id=$2 type=$3

case "$event $type" in
'XIDeviceEnabled XISlaveKeyboard')
    setxkbmap vl,no -option 'grp:rctrl_rshift_toggle,ctrl:swapcaps'
esac
